name: CI/CD - Aula 6


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Etapa 1
        run: echo "Baixando dependencias"
      
      - name: Etapa 2
        run: echo "Lint"
      
      - name: Etapa 3
        run: echo "Testes unitarios"
      
      - name: Etapa 4
        run: echo "Build"
      
      - name: Instalar dependencias
        run: npm ci
      
      - name: Instalar ferramenta de versao
        run: npm install -g semver
      
      - name: Incrementar vers√£o e criar tag
        run: |
          version=$(git tag --sort=-v:refname | head -n 1)
          echo "√öltima vers√£o encontrada: $version"

          if [ -z "$version" ]; then
            version="0.0.0"
          fi

          IFS='.' read -ra ver <<< "$version"
          MAJOR=${ver[0]}
          MINOR=${ver[1]}
          PATCH=${ver[2]}
          PATCH=$((PATCH+1))
          version="$MAJOR.$MINOR.$PATCH"
          echo "Nova vers√£o: $version"

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git tag "v$version"
          git push origin "v$version"

 # üöÄ DOCKER PASSO 1: Login no Docker Hubb
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # üöÄ DOCKER PASSO 2: Build da imagem Docker
      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-angular:latest -f Dockerfile .

      # üöÄ DOCKER PASSO 3: Push da imagem para o Docker Hub
      - name: Push da imagem Docker
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-angular:latest
      
      # üöÄ DOCKER PASSO 4: publicar tags de vers√£o no Docker Hub (SemVer, branch, SHA)
      - name: Docker meta (extra tags & labels)
        id: meta_extra
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-angular
          tags: |
            # SemVer quando push de tag vX[.Y[.Z]]
            type=semver,pattern={{version}},prefix=,enable={{is_tag}}
            type=semver,pattern={{major}}.{{minor}},prefix=,enable={{is_tag}}
            type=semver,pattern={{major}},prefix=,enable={{is_tag}}

            # (Opcional) tag com nome da branch (ex.: feature/minha-feature)
            type=ref,event=branch

            # (Opcional) tag com SHA curto do commit (ex.: :sha-1a2b3c4)
            type=sha,format=short
          labels: |
            org.opencontainers.image.title=frontend-angular
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.run_id }}

      - name: Build & Push (extra tags)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_extra.outputs.tags }}
          labels: ${{ steps.meta_extra.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
